# Generated by Django 3.2.4 on 2021-06-19 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20210610_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
