# Generated by Django 3.2.4 on 2021-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
